export default function propsProvider(props) {
    const {
        t,
        columns,
        dataSource,
        locale,
        handleActionButtonEditClick,
        handleActionButtonDeleteClick,
        handleActionButtonTurnOffClick,
        handleActionButtonTurnOnClick,
        ExpandedRowRenderSelection,
        handleQuickTurnOffConfirm,
        handleQuickActionButtonTurnOnClick,
        handleQuickDeleteConfirm,
        extraColumns,
        handleShowQrCodeClick,
        switchActionColumn,
        handleActionButtonViewClick,
        parentData,
    } = props;
    return {
        t,
        columns,
        dataSource,
        locale,
        handleActionButtonEditClick,
        handleActionButtonDeleteClick,
        handleActionButtonTurnOffClick,
        handleActionButtonTurnOnClick,
        ExpandedRowRenderSelection,
        handleQuickTurnOffConfirm,
        handleQuickActionButtonTurnOnClick,
        handleQuickDeleteConfirm,
        extraColumns,
        handleShowQrCodeClick,
        switchActionColumn,
        handleActionButtonViewClick,
        parentData,
    };
}
