export default function propsProvider(props) {
    const {
        history,
        dispatch,
        t,
        currentBookingData,
        handlePrintBillClick,
        handleViewBookingDetailClick,
        handlePayBillClick,
        cardLoading,
        handleCompleteOrderClick,
        openViewModel,
        viewData,
        handleViewCancelClick,
        loadingTable,
        columns,
        tableData,
        handleActionButtonViewClick,
        expandedRowRenderSelection,
    } = props;
    return {
        history,
        dispatch,
        t,
        currentBookingData,
        handlePrintBillClick,
        handleViewBookingDetailClick,
        handlePayBillClick,
        cardLoading,
        handleCompleteOrderClick,
        openViewModel,
        viewData,
        handleViewCancelClick,
        loadingTable,
        columns,
        tableData,
        handleActionButtonViewClick,
        expandedRowRenderSelection,
    };
}
